---
title: "MultiLinear"
output: html_document
---

# Intro

## 1. Library

```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(GGally)
library(ggplot2)
library(car)
library(lmtest)
library(MLmetrics)
library(readxl)
library(FactoMineR)
library(caret)
library(e1071)
library(rsample)
library(nnet)

options(scipen = 999)
```

### 1.1 Load Data Test

```{r}
secB <- read_excel("data/UAS_PCA dan Multi Linear Regression.xlsx")
glimpse(secB)
head(secB)
```

### 1.2 Cek NA

```{r}
colSums(is.na(secB))
```

### 1.3 Normalisasi Data

```{r}
secB$Saving <- (secB$Saving - min(secB$Saving))/(max(secB$Saving) - min(secB$Saving))
secB$Deposit <- (secB$Deposit - min(secB$Deposit))/(max(secB$Deposit) - min(secB$Deposit))
secB$KK <- (secB$KK - min(secB$KK))/(max(secB$KK) - min(secB$KK))
secB$`Tab Bisnis` <- (secB$`Tab Bisnis` - min(secB$`Tab Bisnis`))/(max(secB$`Tab Bisnis`) - min(secB$`Tab Bisnis`))
secB$`Limit Kredit Mortgage` <- (secB$`Limit Kredit Mortgage` - min(secB$`Limit Kredit Mortgage`))/(max(secB$`Limit Kredit Mortgage`) - min(secB$`Limit Kredit Mortgage`))
```

```{r}
data.raw = secB
dim(data.raw)
length(data.raw$Product_holding)
data.raw[data.raw==""] <- NA
sapply(data.raw, function(x) sum(is.na(x)))
colSums(is.na(data.raw))
sapply(data.raw, function(x) length(unique(x)))
secB$Product_holding <- as.factor(secB$Product_holding)
set.seed(733)
ind <- sample(2, nrow(secB), replace = TRUE, prob = c(0.7, 0.3))
training <- secB[ind==1,]
testing <- secB[ind==2,]
```

## 2. PCA

```{r}
myPr <- prcomp(secB[, 7:13])
#prcomp(~ Income + `Tab Bisnis`, data = secB)
plot (secB$Income, secB$`Tab Bisnis`)
plot (scale(secB$Income), scale(secB$`Tab Bisnis`))
myPr
summary(myPr)
plot(myPr, type = "l")
biplot(myPr, scale = 0)
```

## 3. Multi Linear Regression

```{r}
training$Product_holding <- relevel(training$Product_holding, ref="1")
mod <- multinom(Product_holding~., data = training)
summary(mod)
z <- summary(mod)$coefficients/summary(mod)$standard.errors
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
```

```{r}
p <- predict(mod, training)
head(p)
head(training$Product_holding)
tab1 <- table(p, training$Product_holding)
tab1
1- sum(diag(tab))/sum(tab)
p1 <- predict(mod, testing)
tab2 <- table(p1, testing$Product_holding)
tab2

1 - sum(diag(tab1))/sum(tab1)
table(training$Product_holding)

n <- table(training$Product_holding)
n/sum(n)

tab1/colSums(tab1)
tab2/colSums(tab2)
```
